### ISSUE TITLE
Harvey_Mortuos.maxpat uses jsChord.js

### ISSUE THREAD

**Issue by mzed** [CNMAT/CNMAT-MMJ-Depot#101]
The jsui in Harvey_Mortuos.maxpat uses jsChord.js.  It would be better to use jsNotation.js.  I notice that both of those are deprecated? So, maybe Harvey_Mortuos should be deprecated, too.

**Comment by EdmundCampion** [comment]
Jeff, please go ahead and remove Harvey_Moruos from Depot.

**Comment by mzed** [comment]
Wow! Fast service!! Thanks for your continued hard work. This repertoire section didn't really grow the way we had imagined, I guess. 

FYI, if jsNotation is history then the whole Computer_Assisted_Composition tutorial should go, too.

Since it's deprecated, would you guys mind if I pulled jsNotation and friends into my own repository? I understand that CNMAT has a big job maintaining the core of the Depot.  I wouldn't mind taking care of some of the things that are really relics of my personal interests.

**Comment by equilet** [comment]
done

**Comment by EdmundCampion** [comment]
Michael,  If you don't mind, let's hold off a bit on your request.  We are in the process of migrating to a Depot 2.0..  At that point, we will remove a number of existing things as well as relocate the legacy Max/MSP courses.  We will also upgrade the Spectral Tutorials in that Depot 2.0.

**Comment by mzed** [comment]
Of course.  You, Jeff, and CNMAT are the caretakers of this body of work and should whatever you think is best with it.
