### ISSUE TITLE
instances of o.route errors

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-MMJ-Depot#38]
Please report the following two cases here:

1. o.route msgs don't reach right inlet because inlet does not exist
2. legacy 'slash' argument yields error because it is currently unsupported

**Comment by equilet** [comment]
this is being addressed in https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/38

**Comment by maccallum** [comment]
Closing---this is covered by #300

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-odot/issues/300
