### ISSUE TITLE
pieceplayer: gain problem

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-MMJ-Depot#49]
The gain ceiling on the Depot/pieceplayers are still set too low.  Solution is to add a range setting (upper end gain) in the patcher called advanced_settings.  Then set the default of that range setting to a value that has much more head room then we currently have.  Be sure that the upper range is posted in the advanced_settings (i.e. represents the current default value). Then limit the maximum gain to some number to avoid people putting in outrageous numbers --

**Comment by equilet** [comment]
OK - looks like Ed's features are in place.  Closing this out for now - if needed, we can reopen later or start another issue in the event that other features are needed.
