### ISSUE TITLE
check up on initialization routine inside of startaudio.maxpat

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-MMJ-Depot#56]
From @mzed 
"There’s something weird going on with startaudio.maxpat and max 7. It seems like the led is passing a 1 and then a 0 really quickly to the output.  This shouldn’t be happening, so it seems like a Max bug.  But, I’m also not sure why the LED is attached to the outlet at all.  Or, why the route set object is there."

**Comment by equilet** [comment]
@mzed -- I think [route set] is ensuring that when [adstatus switch] outputs its state, that the 'set' portion of the 'set 1' or 'set 0' message is turned into a 1/0.  As for the startwindow, I'm not sure I've seen this particular problem.  Can you including a patch here that demonstrates the issue?

**Comment by mzed** [comment]
1) Open 24-basic-sdif.maxpat
2) Click startwindow
Expected: Audio starts
Result: Audio does not start

In fact, I think it starts and stops instantly.

mz


> On  2 Jan , at 14:51 , Jeffrey Lubow <notifications@github.com> wrote:
> 
> @mzed <https://github.com/mzed> -- I think [route set] is ensuring that when [adstatus switch] outputs its state, that the 'set' portion of the 'set 1' or 'set 0' message is turned into a 1/0. As for the startwindow, I'm not sure I've seen this particular problem. Can you including a patch here that demonstrates the issue?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/56#issuecomment-68570400>.
> 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
michael f. zbyszyński
www.mikezed.com
z@mikezed.com

**Comment by mzed** [comment]
PS — I’m running CNMAT-CNMAT-MMJ-Depot-ef44fd1 in Max 7, build: 884379c, OS X.X.1

mz

> On  2 Jan , at 14:55 , Michael Zbyszyński <z@mikezed.com> wrote:
> 
> 1) Open 24-basic-sdif.maxpat
> 2) Click startwindow
> Expected: Audio starts
> Result: Audio does not start
> 
> In fact, I think it starts and stops instantly.
> 
> mz
> 
> 
>> On  2 Jan , at 14:51 , Jeffrey Lubow <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> @mzed <https://github.com/mzed> -- I think [route set] is ensuring that when [adstatus switch] outputs its state, that the 'set' portion of the 'set 1' or 'set 0' message is turned into a 1/0. As for the startwindow, I'm not sure I've seen this particular problem. Can you including a patch here that demonstrates the issue?
>> 
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/56#issuecomment-68570400>.
>> 
> 
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> michael f. zbyszyński
> www.mikezed.com <http://www.mikezed.com/>
> z@mikezed.com <mailto:z@mikezed.com>
> 
> 
> 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
michael f. zbyszyński
www.mikezed.com
z@mikezed.com

**Comment by mzed** [comment]
Pretty sure this is a Max bug.  Try this:


<pre><code>
----------begin_max5_patcher----------
459.3ocuTtsaaCCCF9Z6mBAcsyfriyog9lTLTnXQjpNaICI5lTTz8rOcvdIc
0wIqYn2PaRSS8+IRoWSSna0G.Kk7cx8jjjWSSRBg7AR58SnM7CU0baHMZkto
ATHMK9MDNfg32MaVUsr5mjFX3asbr5QoZ2CFnBiqQNay2XYjhBuMeAK33rje
z+ORQnZ5sOMKmMTHUWitCqALHAVeTK9RMDx9j7jpgzx8wdKM0axtR3P8tc0S
o+MA4mWtLH7xA6Xxe8wxX3M.BlG.EeaTxrQIK+rjESBeoEh5fJcsf+rp2L2M
f0x2AenoZQtA2KUB89I1TlyN1SWUN79X6IKo2J2mA5hOAzJXuSSefYAu5WWD
1kK714qlB1xaZ78+HQsF2zBgKrWDq7EgA6ESxUwW9wxyvkiHjicVhcuzAzko
iM2+Xy7onKeb5J9GFQyl534o80PFzZo5uuBNffO962Tr5NS0vxzKVxQJDfEk
JNJ0pSxY86x4QoP.pS6WBo0eqTXGfMZy4ZUyxqPMkeYp4Z1aJ9jpI133ssOC
FaeICBwM29j13cWkEbkpnanhTC7rbH+vkdTtwMqhtA0NSbr5v53kjzFs.LpN
Y+gF2J+V5ugNnErU
-----------end_max5_patcher-----------
</code></pre>


I see 1, then 0 in the max window.

mz

> On  2 Jan , at 15:00 , Michael Zbyszyński <z@mikezed.com> wrote:
> 
> PS — I’m running CNMAT-CNMAT-MMJ-Depot-ef44fd1 in Max 7, build: 884379c, OS X.X.1
> 
> mz
> 
>> On  2 Jan , at 14:55 , Michael Zbyszyński <z@mikezed.com <mailto:z@mikezed.com>> wrote:
>> 
>> 1) Open 24-basic-sdif.maxpat
>> 2) Click startwindow
>> Expected: Audio starts
>> Result: Audio does not start
>> 
>> In fact, I think it starts and stops instantly.
>> 
>> mz
>> 
>> 
>>> On  2 Jan , at 14:51 , Jeffrey Lubow <notifications@github.com <mailto:notifications@github.com>> wrote:
>>> 
>>> @mzed <https://github.com/mzed> -- I think [route set] is ensuring that when [adstatus switch] outputs its state, that the 'set' portion of the 'set 1' or 'set 0' message is turned into a 1/0. As for the startwindow, I'm not sure I've seen this particular problem. Can you including a patch here that demonstrates the issue?
>>> 
>>> —
>>> Reply to this email directly or view it on GitHub <https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/56#issuecomment-68570400>.
>>> 
>> 
>> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>> michael f. zbyszyński
>> www.mikezed.com <http://www.mikezed.com/>
>> z@mikezed.com <mailto:z@mikezed.com>
>> 
>> 
>> 
> 
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> michael f. zbyszyński
> www.mikezed.com <http://www.mikezed.com/>
> z@mikezed.com <mailto:z@mikezed.com>
> 
> 
> 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
michael f. zbyszyński
www.mikezed.com
z@mikezed.com

**Comment by equilet** [comment]
I tried the bug and I don't get the same behavior.  Please DL the fix I implemented for startaudio and LMK if you still have problems.  Thanks!

**Comment by mzed** [comment]
Really? The startwindow message is entirely broken for me in the current Max. I reported it to the beta list; maybe I'm just lucky.

mz


> On  2 Jan , at 15:15 , Jeffrey Lubow <notifications@github.com> wrote:
> 
> I tried the bug and I don't get the same behavior. Please DL the fix I implemented for startaudio and LMK if you still have problems. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/56#issuecomment-68571960>.
> 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
michael f. zbyszyński
www.mikezed.com
z@mikezed.com

**Comment by mzed** [comment]
The new startaudio looks and works a lot better. Thanks.

mz


> On  2 Jan , at 15:18 , Michael Zbyszyński <z@mikezed.com> wrote:
> 
> Really? The startwindow message is entirely broken for me in the current Max. I reported it to the beta list; maybe I'm just lucky.
> 
> mz
> 
> 
>> On  2 Jan , at 15:15 , Jeffrey Lubow <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> I tried the bug and I don't get the same behavior. Please DL the fix I implemented for startaudio and LMK if you still have problems. Thanks!
>> 
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/56#issuecomment-68571960>.
>> 
> 
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> michael f. zbyszyński
> www.mikezed.com <http://www.mikezed.com/>
> z@mikezed.com <mailto:z@mikezed.com>
> 
> 
> 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
michael f. zbyszyński
www.mikezed.com
z@mikezed.com

**Comment by equilet** [comment]
Sure thing!
