### ISSUE TITLE
m29 standalone crashes in lab

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-MMJ-Depot#61]
From Matt:

I copied you this morning on an email to Willa about an error I have witnessed over the last two labs.  The error manifests as "spinning wheel"/crashed program. This effects c. 5-7% of lab computers for any given patch that is opened, so c.2 machines of 35 per patch.  The problem is erratic in the sense that it doesn't seem to repeatedly target specific lab machines and in the sense that the software works for the majority of the users at any one time, suggesting to me that the problem might not be in the given standalone applications. But maybe I'm wrong about that. At one point, Willa suggested that it might have something to do with memory allocation on the lab machines.  The only temporary fix we have adopted so far is to have GSIs pass new copies of the standalone from their share folder to affected students. This seems to work most but not all of the time.

**Comment by equilet** [comment]
From Ilya:

The problem with lab machines is more than the % provided, I have around 10 machines spinning wheels.  And they sometimes start spinning wheels after not spinning originally, which may be a hint...

I find it suspect that (a) I had NO ISSUES on the instructor machine, and (b) that the problem is as erratic as it is. I would recommend looking at "top" in the terminal and look at memory. I will do this next time I'm at the lab - the weird delayed nature of the problem hints at an issue that is extremely challenging to track. 

Thanks a lot for the remarkable work with standalones. These issues come up and things are hard, but I think we have the best ones I've seen yet and I'm very grateful for your work. Instructor machine, at least, is rocking them solid without a single (!!!) crash or issue, across three hours of lab time, with everything turned on.

**Comment by equilet** [comment]
Thanks for the feedback.
It wouldn't kill me to rebuild all of them, but if you can narrow the issue down a bit, it'd be greatly appreciated - LMK about your findings w/ `top` and if you have specific steps to reproduce, that'd also be helpful.  I need details like the following:

1. what OS
2. what version of runtime or Max
3. what version of the standalones (or where you got them)
4. what created date of the files you're loading
5. which apps this is an issue on (or is it all of them?)
6. specs of the Mac computers running these

To be honest, the issues Ilya/Matt are mentioning sound a bit unrelated to Ed's problem, so any clarification would be great.

**Comment by equilet** [comment]
From Matt:

The percentage I meant to give was an estimate of afflicted computers at any given moment, usually with one standalone. In other words up to about 3 computers could be having spinning wheel issues at any given time. So, 10+ computers total could be affected over the course of a lab but not at the same time. This is what I observed in two sessions of the previous lab on different days.

Ilya did you experience a higher percentage, like 30% malfunctiong computers at any given moment, on this most recent lab? Or did you experience 10 computers each having temporary spinning wheel issues at different times over the course of the whole lab?  

Thanks,
Matt

**Comment by equilet** [comment]
"Willa suggested that it might have something to do with memory allocation on the lab machines"

I have a hard time believing that this could be even remotely related to memory allocation.  I'm crossing this off my list of ideas to check.

**Comment by equilet** [comment]
@mattschumaker - Thanks for these details, but I still need specs.

- Version of Max - you specified 6, but I need a version number.  Yes we're using standalones, but If I want to put in a hotfix for a critical change we may need to use Max since I don't have the time to rebuild all standalones right now.

- Created date of the files you're loading - I need the creation date of the standalone app files (packages).  

Please review this info and post here.

---

A couple of notes:

- Original location of standalones: This concerns me. 
We should never be pulling standalones from a hard drive - I'd fee much safer with all of this if we could agree to use the location [here](https://berkeley.app.box.com/files/0/f/710725695/MUSIC29_standalones), which we'd used last time anything got updated.

**Comment by equilet** [comment]
loadbang -> dsp init will be present in all future builds.

**Comment by mattschumaker** [comment]
Version of Max:
6.1.8 (9fafea67)(32-bit)

Standalone Creation Dates:
Soundfile Presenter: April 7, 2014 (modified 1-22-15)
Additive Synthesis Introduction: March 6, 2013 (modified 1-22-15)
Frequency Bands and Filtering: March 6, 2013 (modified 1-22-15)
Keymouse Synthesizer: April 11, 2013 (modified 1-22-15)
Synthesized Human Voice: March 6, 2013 (modified 1-22-15)
Waveform Builder: April 11, 2013 (modified 1-22-15)
Waveforms and Hearing I: March 6, 2103 (modified 1-22-15)
Waveforms and Hearing II: April 11, 2103 (modified 1-22-15)
Soundfile Interpolation Space: January 28, 2014 (modified 2-22-2015)
Audition and Decide II: March 14, 2013 (modified 2-11-2015)
Polyrhythm Explorer: March 27, 2013 (modified 2-11-2015)
Temporary Beat Slicer: March 27, 2013 (modified 1-22-2015)
Plucked String Playspace: April 30, 2013 (modified 1-22-2015)
Plucked String Simulation: March 27, 2013 (modified 1-22-2015)

**Comment by equilet** [comment]
crashes have been resolved, and were happening based on DSP initialization issues.  closing in favor of https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/40
