### ISSUE TITLE
soundfile interpolation space - buffer fail when loading previous configuration

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-MMJ-Depot#63]
From @mattschumaker:

I think that I found a bug using the new soundfile space interpolation space today.  Sometimes when it loads a saved preset from disk the sound will not play at all.  For instance, in music 29 lab 3, if I load "01_emotional_inferences-solution.txt" all the sound will stop playing and it won't start back up again until I restart the app. (See the Max window error messages below.)

If this is a bug, then I think that we will just use the old version of the  soundfile interpolation space app for lab 3 starting on Friday.  We can change to an updated version for labs 4 or 6 later, if we want.

---

buffer~: doesn't understand "z15Bell.aif"
buffer~: doesn't understand "z14Bell.aif"
buffer~: doesn't understand "z13_ia.aif"
buffer~: doesn't understand "z12_ia.aif"
buffer~: doesn't understand "z11_ia.aif"
buffer~: doesn't understand "z09_ia.aif"
buffer~: doesn't understand "z03_ia.aif"
buffer~: doesn't understand "z02_ia.aif"
buffer~: doesn't understand "z00_ia.aif"
buffer~: doesn't understand "15Bell.aif"
buffer~: doesn't understand "14Bell.aif"
buffer~: doesn't understand "13_ia.aif"
buffer~: doesn't understand "12_ia.aif"
buffer~: doesn't understand "11_ia.aif"
buffer~: doesn't understand "09_ia.aif"
buffer~: doesn't understand "03_ia.aif"
buffer~: doesn't understand "02_ia.aif"
buffer~: doesn't understand "00_ia.aif"
num_soundfiles: 9
o.route: The set message to o.route has been deprecated and will be removed in the future
num_soundfiles: 9
buffer~: doesn't understand "z15Bell.aif"
buffer~: doesn't understand "z14Bell.aif"
buffer~: doesn't understand "z13_ia.aif"
buffer~: doesn't understand "z12_ia.aif"
buffer~: doesn't understand "z11_ia.aif"
buffer~: doesn't understand "z09_ia.aif"
buffer~: doesn't understand "z03_ia.aif"
buffer~: doesn't understand "z02_ia.aif"
buffer~: doesn't understand "z00_ia.aif"
num_soundfiles: 9
buffer~: doesn't understand "z15Bell.aif"
buffer~: doesn't understand "z14Bell.aif"
buffer~: doesn't understand "z13_ia.aif"
buffer~: doesn't understand "z12_ia.aif"
buffer~: doesn't understand "z11_ia.aif"
buffer~: doesn't understand "z09_ia.aif"
buffer~: doesn't understand "z03_ia.aif"
buffer~: doesn't understand "z02_ia.aif"
buffer~: doesn't understand "z00_ia.aif"

**Comment by equilet** [comment]
OK, I put a fix in for this.  @mattschumaker - Can you please do some testing with the Soundfile_Interpolation_Space patch by downloading a fresh copy of the depot and attempting the same sequence of steps you tried to get the errors above?

**Comment by mattschumaker** [comment]
This version of Soundfile Interpolation will load presets and play so long as the folder of soundfiles is dropped in before the preset is loaded.  Loading a preset does not appear to load related soundfiles.

I assume that this is expected behavior, so the patch seems to be working correctly. The issue has been dealt with.

However, encountered two errors in Max window on opening the patch:
"m29dspinit: No such object"
"o.route argument 1 is not an OSC address"

These didn't appear to impede performance. I can email you screenshot of Max window if wanted.

I am assuming this patch is not meant to load mp3s.

**Comment by equilet** [comment]
try again

**Comment by equilet** [comment]
verified the various fixes on this with Matt.  Closing out.
