### ISSUE TITLE
add gliss engine to depot

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-MMJ-Depot#75]
This tool needs to be documented and added Depot

**Comment by equilet** [comment]
this is the replacement of https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/65

**Comment by equilet** [comment]
noting quickly here that the final version was "3" although there will be no revision name in the initial depot entry

**Comment by equilet** [comment]
added.
