### ISSUE TITLE
for Music 29: playing real-time audio into the "sonogram frequency analysis"

### ISSUE THREAD

**Issue by kulpajj** [CNMAT/CNMAT-MMJ-Depot#99]
for Music29, Nils wants to play real-time /adc~ input into the “sonogram frequency analysis” stand-alone that is included in the Lab modules.

**Comment by equilet** [comment]
can he just send audio via [send~ signalX] ?

**Comment by equilet** [comment]
<img width="119" alt="screen shot 2018-02-14 at 11 35 09 am" src="https://user-images.githubusercontent.com/2237372/36224024-21942220-117b-11e8-8fd5-270b97b1d3a5.png">

**Comment by equilet** [comment]
In this case, he doesn't have to use the standalone; just Max
